---
creds:
  username: "{{ ansible_user }}"
  password: "{{ ansible_pass }}"
  host: "{{ ansible_host }}"

base_line:
  domain: opticoreit.com
  ssh_ver: 2
  ssh_tries: 3

loopbacks:
  - id: 10
    ip: 20.0.0.10
    mask: 255.255.255.255
    ospf_area: 10
  - id: 20
    ip: 20.0.0.20
    mask: 255.255.255.255
    ospf_area: 20
  - id: 30
    ip: 20.0.0.30
    mask: 255.255.255.255
    ospf_area: 30

snmp:
  contact: Omid.Mortazavi@opticoreit.com
  location: Magnus House, Ground Floor
  ro:
    - public123
    - opticore123
  rw:
    - private123
